name: dvf
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.6
  - conda-forge::numpy
  - conda-forge::theano=1.0.3
  - conda-forge::keras=2.2.4
  - conda-forge::scikit-learn
  - conda-forge::biopython
  - conda-forge::h5py=2.10.0
  - conda-forge::gxx=12.2.0
